<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\CSMatches\" />
    <Folder Include="wwwroot\images\cs\maps\" />
    <Folder Include="wwwroot\images\cs\teams\" />
  </ItemGroup>

</Project>
