-- PersonalTools canonical database schema.
-- DESTRUCTIVE: resets PersonalTools accounts, sessions and user-owned application data.
CREATE DATABASE IF NOT EXISTS PersonalTools CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE PersonalTools;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS CaseOpeningHistory;
DROP TABLE IF EXISTS PasteBinFiles;
DROP TABLE IF EXISTS PasteBinPastes;
DROP TABLE IF EXISTS PasteBinSettings;
DROP TABLE IF EXISTS TrackerSettings;
DROP TABLE IF EXISTS TrackerItems;
DROP TABLE IF EXISTS CSPlayerReports;
DROP TABLE IF EXISTS CSDemoCatalog;
DROP TABLE IF EXISTS ApplicationLogs;
DROP TABLE IF EXISTS CSMatches;
DROP TABLE IF EXISTS CSMatchProfiles;
DROP TABLE IF EXISTS CSActiveDutyMaps;
DROP TABLE IF EXISTS AppSettings;
DROP TABLE IF EXISTS DashboardWeatherLocations;
DROP TABLE IF EXISTS DashboardWidgetOrders;
DROP TABLE IF EXISTS TrackedSkins;
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS QuickLinks;
DROP TABLE IF EXISTS UserSessions;
DROP TABLE IF EXISTS Users;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE Users (UserId CHAR(36) NOT NULL,Email VARCHAR(254) NOT NULL,DisplayName VARCHAR(100) NOT NULL,PasswordHash VARCHAR(512) NOT NULL,SteamId CHAR(17) NULL,IsActive TINYINT(1) NOT NULL DEFAULT 1,CreatedUtc DATETIME NOT NULL,PRIMARY KEY(UserId),UNIQUE KEY UX_Users_Email(Email),UNIQUE KEY UX_Users_SteamId(SteamId));
CREATE TABLE UserSessions (SessionId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,TokenHash CHAR(64) NOT NULL,ExpiresUtc DATETIME NOT NULL,UserAgent VARCHAR(512) NOT NULL,CreatedUtc DATETIME NOT NULL,PRIMARY KEY(SessionId),KEY IX_UserSessions_UserId(UserId),KEY IX_UserSessions_ExpiresUtc(ExpiresUtc),CONSTRAINT FK_UserSessions_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE QuickLinks (QuickLinkId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,Title VARCHAR(100) NOT NULL,Url VARCHAR(2048) NOT NULL,IconClass VARCHAR(100) NULL,SortOrder INT NOT NULL DEFAULT 0,CreatedUtc DATETIME NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(QuickLinkId),KEY IX_QuickLinks_UserId_SortOrder(UserId,SortOrder),CONSTRAINT FK_QuickLinks_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE Notes (NoteId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,Title VARCHAR(200) NOT NULL,Body MEDIUMTEXT NOT NULL,SortOrder INT NOT NULL DEFAULT 0,CreatedUtc DATETIME NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(NoteId),KEY IX_Notes_UserId_SortOrder(UserId,SortOrder),CONSTRAINT FK_Notes_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE TrackedSkins (SkinId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,Name VARCHAR(200) NOT NULL,Weapon VARCHAR(100) NOT NULL,Exterior VARCHAR(100) NOT NULL,MarketHashName VARCHAR(255) NOT NULL,ExternalImageUrl VARCHAR(2048) NOT NULL,PurchasePrice DECIMAL(12,2) NOT NULL DEFAULT 0,CurrentPrice DECIMAL(12,2) NULL,PurchaseDate DATE NULL,Notes TEXT NOT NULL,CreatedUtc DATETIME NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(SkinId),KEY IX_TrackedSkins_UserId_UpdatedUtc(UserId,UpdatedUtc),CONSTRAINT FK_TrackedSkins_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE DashboardWidgetOrders (UserId CHAR(36) NOT NULL,WidgetKey VARCHAR(50) NOT NULL,SortOrder INT NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(UserId,WidgetKey),CONSTRAINT FK_DashboardWidgetOrders_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE DashboardWeatherLocations (WeatherLocationId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,DisplayName VARCHAR(100) NOT NULL,Latitude DECIMAL(9,6) NOT NULL,Longitude DECIMAL(9,6) NOT NULL,CreatedUtc DATETIME NOT NULL,PRIMARY KEY(WeatherLocationId),KEY IX_DashboardWeatherLocations_UserId_CreatedUtc(UserId,CreatedUtc),CONSTRAINT FK_DashboardWeatherLocations_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE CSMatchProfiles (ProfileId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,Name VARCHAR(100) NOT NULL,SteamId CHAR(17) NOT NULL,AvatarUrl VARCHAR(2048) NULL,CreatedUtc DATETIME NOT NULL,PRIMARY KEY(ProfileId),KEY IX_CSMatchProfiles_UserId(UserId),CONSTRAINT FK_CSMatchProfiles_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE CSMatches (MatchId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,ProfileId CHAR(36) NULL,StartSide VARCHAR(2) NOT NULL,MapName VARCHAR(100) NOT NULL,GameType VARCHAR(100) NOT NULL,TeamScore INT NOT NULL,OpponentScore INT NOT NULL,OvertimeCount INT NOT NULL DEFAULT 0,LeetifyMatchId VARCHAR(100) NULL,PlayedUtc DATETIME NOT NULL,CreatedUtc DATETIME NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(MatchId),KEY IX_CSMatches_UserId_ProfileId(UserId,ProfileId),KEY IX_CSMatches_UserId_CreatedUtc(UserId,CreatedUtc),UNIQUE KEY UX_CSMatches_UserId_ProfileId_LeetifyMatchId(UserId,ProfileId,LeetifyMatchId),CONSTRAINT FK_CSMatches_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE,CONSTRAINT FK_CSMatches_Profiles FOREIGN KEY(ProfileId) REFERENCES CSMatchProfiles(ProfileId) ON DELETE CASCADE);
CREATE TABLE CSPlayerReports (ReportId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,Steam64Id CHAR(17) NOT NULL,CreatedUtc DATETIME NOT NULL,PRIMARY KEY(ReportId),UNIQUE KEY UX_CSPlayerReports_UserId_Steam64Id(UserId,Steam64Id),KEY IX_CSPlayerReports_Steam64Id(Steam64Id),CONSTRAINT FK_CSPlayerReports_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE CSDemoCatalog (DemoId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,Steam64Id CHAR(17) NOT NULL,LeetifyMatchId VARCHAR(100) NOT NULL,MapName VARCHAR(100) NOT NULL,GameType VARCHAR(100) NOT NULL,TeamScore INT NOT NULL,OpponentScore INT NOT NULL,IsWin TINYINT(1) NOT NULL,ReplayUrl VARCHAR(2048) NULL,IsAvailable TINYINT(1) NOT NULL DEFAULT 0,PlayedAtUtc DATETIME NOT NULL,RefreshedUtc DATETIME NOT NULL,PRIMARY KEY(DemoId),UNIQUE KEY UX_CSDemoCatalog_User_Steam_Match(UserId,Steam64Id,LeetifyMatchId),KEY IX_CSDemoCatalog_User_Steam_Played(UserId,Steam64Id,PlayedAtUtc),CONSTRAINT FK_CSDemoCatalog_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE ApplicationLogs (LogId CHAR(36) NOT NULL,CapturedUtc DATETIME(6) NOT NULL,LogLevel TINYINT UNSIGNED NOT NULL,EventId INT NOT NULL DEFAULT 0,EventName VARCHAR(250) NULL,Category VARCHAR(500) NOT NULL,Message TEXT NOT NULL,ExceptionText MEDIUMTEXT NULL,PRIMARY KEY(LogId),KEY IX_ApplicationLogs_CapturedUtc(CapturedUtc),KEY IX_ApplicationLogs_Level_CapturedUtc(LogLevel,CapturedUtc));
CREATE TABLE AppSettings (UserId CHAR(36) NOT NULL,SettingKey VARCHAR(80) NOT NULL,SettingValue MEDIUMTEXT NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(UserId,SettingKey),CONSTRAINT FK_AppSettings_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE CSActiveDutyMaps (MapPoolId CHAR(36) NOT NULL,MapName VARCHAR(80) NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(MapPoolId),UNIQUE KEY UX_CSActiveDutyMaps_MapName(MapName));
CREATE TABLE TrackerItems (ItemId CHAR(36) NOT NULL,Type VARCHAR(10) NOT NULL,Title VARCHAR(200) NOT NULL,Description TEXT NOT NULL,Area VARCHAR(50) NOT NULL,Status VARCHAR(20) NOT NULL DEFAULT 'Open',SortOrder INT NOT NULL DEFAULT 0,CreatedByUserId CHAR(36) NULL,AssignedToUserId CHAR(36) NULL,ResolvedUtc DATETIME NULL,ShowOnDashboard TINYINT(1) NOT NULL DEFAULT 0,CreatedUtc DATETIME NOT NULL,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(ItemId),KEY IX_TrackerItems_Status_SortOrder(Status,SortOrder),CONSTRAINT FK_TrackerItems_Users FOREIGN KEY(CreatedByUserId) REFERENCES Users(UserId) ON DELETE SET NULL,CONSTRAINT FK_TrackerItems_AssignedTo FOREIGN KEY(AssignedToUserId) REFERENCES Users(UserId) ON DELETE SET NULL);
CREATE TABLE TrackerSettings (Id TINYINT NOT NULL,AutoCloseAfterDays INT NOT NULL DEFAULT 5,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(Id));
INSERT INTO TrackerSettings (Id, AutoCloseAfterDays, UpdatedUtc) VALUES (1, 5, UTC_TIMESTAMP());
CREATE TABLE PasteBinSettings (Id TINYINT NOT NULL,MaximumUploadSizeMb INT NOT NULL DEFAULT 50,UpdatedUtc DATETIME NOT NULL,PRIMARY KEY(Id));
INSERT INTO PasteBinSettings (Id,MaximumUploadSizeMb,UpdatedUtc) VALUES (1,50,UTC_TIMESTAMP());
CREATE TABLE PasteBinPastes (PasteId CHAR(36) NOT NULL,CreatedByUserId CHAR(36) NOT NULL,ShortCode VARCHAR(16) NOT NULL,Title VARCHAR(200) NOT NULL,Language VARCHAR(30) NOT NULL,Content MEDIUMTEXT NULL,PasswordHash VARCHAR(512) NULL,CreatedUtc DATETIME NOT NULL,ExpiresUtc DATETIME NULL,PRIMARY KEY(PasteId),UNIQUE KEY UX_PasteBinPastes_ShortCode(ShortCode),KEY IX_PasteBinPastes_Active(ExpiresUtc,CreatedUtc),KEY IX_PasteBinPastes_Creator(CreatedByUserId,CreatedUtc),CONSTRAINT FK_PasteBinPastes_Users FOREIGN KEY(CreatedByUserId) REFERENCES Users(UserId) ON DELETE CASCADE);
CREATE TABLE PasteBinFiles (PasteFileId CHAR(36) NOT NULL,PasteId CHAR(36) NOT NULL,OriginalFileName VARCHAR(255) NOT NULL,StoredFileName CHAR(36) NOT NULL,ContentType VARCHAR(150) NOT NULL,FileExtension VARCHAR(20) NOT NULL,FileSizeBytes BIGINT UNSIGNED NOT NULL,CreatedUtc DATETIME NOT NULL,PRIMARY KEY(PasteFileId),UNIQUE KEY UX_PasteBinFiles_PasteId(PasteId),UNIQUE KEY UX_PasteBinFiles_StoredFileName(StoredFileName),CONSTRAINT FK_PasteBinFiles_Pastes FOREIGN KEY(PasteId) REFERENCES PasteBinPastes(PasteId) ON DELETE CASCADE);
CREATE TABLE CaseOpeningHistory (OpeningId CHAR(36) NOT NULL,UserId CHAR(36) NOT NULL,CaseKey VARCHAR(80) NOT NULL,SourceItemId VARCHAR(160) NOT NULL,ItemName VARCHAR(255) NOT NULL,MarketHashName VARCHAR(300) NOT NULL,ImageUrl VARCHAR(2048) NOT NULL,Description TEXT NOT NULL,WeaponName VARCHAR(100) NOT NULL,PatternName VARCHAR(150) NOT NULL,PaintIndex VARCHAR(20) NOT NULL,Phase VARCHAR(50) NOT NULL,RarityKey VARCHAR(30) NOT NULL,RarityName VARCHAR(80) NOT NULL,RarityColor CHAR(7) NOT NULL,Wear VARCHAR(40) NOT NULL,IsStatTrak TINYINT(1) NOT NULL DEFAULT 0,IsRareSpecial TINYINT(1) NOT NULL DEFAULT 0,SupportsStatTrak TINYINT(1) NOT NULL DEFAULT 0,MinFloat DECIMAL(9,6) NULL,MaxFloat DECIMAL(9,6) NULL,FloatValue DECIMAL(9,6) NULL,PatternSeed INT NULL,EstimatedPrice DECIMAL(12,2) NULL,OpenedUtc DATETIME(6) NOT NULL,PRIMARY KEY(OpeningId),KEY IX_CaseOpeningHistory_User_Opened(UserId,OpenedUtc),CONSTRAINT FK_CaseOpeningHistory_Users FOREIGN KEY(UserId) REFERENCES Users(UserId) ON DELETE CASCADE);

DELIMITER $$
DROP PROCEDURE IF EXISTS sp_auth_user_count$$ DROP PROCEDURE IF EXISTS sp_auth_user_get_by_email$$ DROP PROCEDURE IF EXISTS sp_auth_user_get_by_id$$ DROP PROCEDURE IF EXISTS sp_auth_owner_create$$ DROP PROCEDURE IF EXISTS sp_auth_session_create$$ DROP PROCEDURE IF EXISTS sp_auth_session_valid$$ DROP PROCEDURE IF EXISTS sp_auth_session_delete$$ DROP PROCEDURE IF EXISTS sp_auth_user_set_steam_id$$ DROP PROCEDURE IF EXISTS sp_auth_user_clear_steam_id$$ DROP PROCEDURE IF EXISTS sp_auth_user_change_password$$
CREATE PROCEDURE sp_auth_user_count() SELECT COUNT(*) FROM Users$$
CREATE PROCEDURE sp_auth_user_get_by_email(IN p_email VARCHAR(254)) SELECT UserId,Email,DisplayName,PasswordHash,IsActive,SteamId FROM Users WHERE Email=p_email LIMIT 1$$
CREATE PROCEDURE sp_auth_user_get_by_id(IN p_user_id CHAR(36)) SELECT UserId,Email,DisplayName,PasswordHash,IsActive,SteamId FROM Users WHERE UserId=p_user_id LIMIT 1$$
CREATE PROCEDURE sp_auth_owner_create(IN p_user_id CHAR(36),IN p_email VARCHAR(254),IN p_display_name VARCHAR(100),IN p_password_hash VARCHAR(512)) INSERT INTO Users(UserId,Email,DisplayName,PasswordHash,CreatedUtc) VALUES(p_user_id,p_email,p_display_name,p_password_hash,UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_auth_session_create(IN p_session_id CHAR(36),IN p_user_id CHAR(36),IN p_token_hash CHAR(64),IN p_expires_utc DATETIME,IN p_user_agent VARCHAR(512)) INSERT INTO UserSessions(SessionId,UserId,TokenHash,ExpiresUtc,UserAgent,CreatedUtc) VALUES(p_session_id,p_user_id,p_token_hash,p_expires_utc,p_user_agent,UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_auth_session_valid(IN p_session_id CHAR(36),IN p_user_id CHAR(36)) SELECT EXISTS(SELECT 1 FROM UserSessions WHERE SessionId=p_session_id AND UserId=p_user_id AND ExpiresUtc>UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_auth_session_delete(IN p_session_id CHAR(36)) DELETE FROM UserSessions WHERE SessionId=p_session_id$$
CREATE PROCEDURE sp_auth_user_set_steam_id(IN p_user_id CHAR(36),IN p_steam_id CHAR(17)) UPDATE Users SET SteamId=p_steam_id WHERE UserId=p_user_id$$
CREATE PROCEDURE sp_auth_user_clear_steam_id(IN p_user_id CHAR(36)) UPDATE Users SET SteamId=NULL WHERE UserId=p_user_id$$
CREATE PROCEDURE sp_auth_user_change_password(IN p_user_id CHAR(36),IN p_session_id CHAR(36),IN p_password_hash VARCHAR(512)) BEGIN UPDATE Users SET PasswordHash=p_password_hash WHERE UserId=p_user_id AND IsActive=1; IF ROW_COUNT()=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Account is unavailable'; END IF; DELETE FROM UserSessions WHERE UserId=p_user_id AND SessionId<>p_session_id; END$$

DROP PROCEDURE IF EXISTS sp_app_settings_get$$ DROP PROCEDURE IF EXISTS sp_app_settings_set$$
CREATE PROCEDURE sp_app_settings_get(IN p_user_id CHAR(36)) SELECT SettingKey,SettingValue FROM AppSettings WHERE UserId=p_user_id$$
CREATE PROCEDURE sp_app_settings_set(IN p_user_id CHAR(36),IN p_setting_key VARCHAR(80),IN p_setting_value MEDIUMTEXT) INSERT INTO AppSettings(UserId,SettingKey,SettingValue,UpdatedUtc) VALUES(p_user_id,p_setting_key,p_setting_value,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE SettingValue=VALUES(SettingValue),UpdatedUtc=VALUES(UpdatedUtc)$$

DROP PROCEDURE IF EXISTS sp_cs_active_duty_maps_get$$ DROP PROCEDURE IF EXISTS sp_cs_active_duty_maps_set$$
CREATE PROCEDURE sp_cs_active_duty_maps_get() SELECT MapName FROM CSActiveDutyMaps ORDER BY MapName$$
CREATE PROCEDURE sp_cs_active_duty_maps_set(IN p_map_names JSON) BEGIN DELETE FROM CSActiveDutyMaps; INSERT INTO CSActiveDutyMaps(MapPoolId,MapName,UpdatedUtc) SELECT UUID(),selected.MapName,UTC_TIMESTAMP() FROM JSON_TABLE(p_map_names,'$[*]' COLUMNS(MapName VARCHAR(80) PATH '$')) AS selected WHERE selected.MapName IS NOT NULL AND CHAR_LENGTH(TRIM(selected.MapName)) > 0; END$$

DROP PROCEDURE IF EXISTS sp_quick_links_get$$ DROP PROCEDURE IF EXISTS sp_quick_links_create$$ DROP PROCEDURE IF EXISTS sp_quick_links_update$$ DROP PROCEDURE IF EXISTS sp_quick_links_delete$$ DROP PROCEDURE IF EXISTS sp_quick_links_set_order_bulk$$
CREATE PROCEDURE sp_quick_links_get(IN p_user_id CHAR(36)) SELECT QuickLinkId,Title,Url,IconClass,SortOrder,UpdatedUtc FROM QuickLinks WHERE UserId=p_user_id ORDER BY SortOrder,CreatedUtc,QuickLinkId$$
CREATE PROCEDURE sp_quick_links_create(IN p_user_id CHAR(36),IN p_quick_link_id CHAR(36),IN p_title VARCHAR(100),IN p_url VARCHAR(2048),IN p_icon_class VARCHAR(100)) INSERT INTO QuickLinks(QuickLinkId,UserId,Title,Url,IconClass,SortOrder,CreatedUtc,UpdatedUtc) SELECT p_quick_link_id,p_user_id,p_title,p_url,NULLIF(p_icon_class,''),COALESCE(MAX(SortOrder)+1,0),UTC_TIMESTAMP(),UTC_TIMESTAMP() FROM QuickLinks WHERE UserId=p_user_id$$
CREATE PROCEDURE sp_quick_links_update(IN p_user_id CHAR(36),IN p_quick_link_id CHAR(36),IN p_title VARCHAR(100),IN p_url VARCHAR(2048),IN p_icon_class VARCHAR(100)) UPDATE QuickLinks SET Title=p_title,Url=p_url,IconClass=NULLIF(p_icon_class,''),UpdatedUtc=UTC_TIMESTAMP() WHERE QuickLinkId=p_quick_link_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_quick_links_delete(IN p_user_id CHAR(36),IN p_quick_link_id CHAR(36)) DELETE FROM QuickLinks WHERE QuickLinkId=p_quick_link_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_quick_links_set_order_bulk(IN p_user_id CHAR(36),IN p_quick_link_ids JSON) BEGIN UPDATE QuickLinks l INNER JOIN JSON_TABLE(p_quick_link_ids,'$[*]' COLUMNS(SortOrder FOR ORDINALITY,QuickLinkId CHAR(36) PATH '$')) p ON p.QuickLinkId=l.QuickLinkId SET l.SortOrder=p.SortOrder WHERE l.UserId=p_user_id; END$$

DROP PROCEDURE IF EXISTS sp_notes_get$$ DROP PROCEDURE IF EXISTS sp_notes_create$$ DROP PROCEDURE IF EXISTS sp_notes_update$$ DROP PROCEDURE IF EXISTS sp_notes_delete$$ DROP PROCEDURE IF EXISTS sp_notes_set_order_bulk$$
CREATE PROCEDURE sp_notes_get(IN p_user_id CHAR(36)) SELECT NoteId,Title,Body,SortOrder,CreatedUtc,UpdatedUtc FROM Notes WHERE UserId=p_user_id ORDER BY SortOrder,UpdatedUtc DESC$$
CREATE PROCEDURE sp_notes_create(IN p_user_id CHAR(36),IN p_note_id CHAR(36),IN p_title VARCHAR(200),IN p_body MEDIUMTEXT) INSERT INTO Notes(NoteId,UserId,Title,Body,SortOrder,CreatedUtc,UpdatedUtc) SELECT p_note_id,p_user_id,p_title,p_body,COALESCE(MAX(SortOrder)+1,0),UTC_TIMESTAMP(),UTC_TIMESTAMP() FROM Notes WHERE UserId=p_user_id$$
CREATE PROCEDURE sp_notes_update(IN p_user_id CHAR(36),IN p_note_id CHAR(36),IN p_title VARCHAR(200),IN p_body MEDIUMTEXT) UPDATE Notes SET Title=p_title,Body=p_body,UpdatedUtc=UTC_TIMESTAMP() WHERE NoteId=p_note_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_notes_delete(IN p_user_id CHAR(36),IN p_note_id CHAR(36)) DELETE FROM Notes WHERE NoteId=p_note_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_notes_set_order_bulk(IN p_user_id CHAR(36),IN p_note_ids JSON) BEGIN UPDATE Notes n INNER JOIN JSON_TABLE(p_note_ids,'$[*]' COLUMNS(SortOrder FOR ORDINALITY,NoteId CHAR(36) PATH '$')) p ON p.NoteId=n.NoteId SET n.SortOrder=p.SortOrder WHERE n.UserId=p_user_id; END$$

DROP PROCEDURE IF EXISTS sp_tracked_skins_get$$ DROP PROCEDURE IF EXISTS sp_tracked_skins_create$$ DROP PROCEDURE IF EXISTS sp_tracked_skins_update$$ DROP PROCEDURE IF EXISTS sp_tracked_skins_delete$$
CREATE PROCEDURE sp_tracked_skins_get(IN p_user_id CHAR(36)) SELECT SkinId,Name,Weapon,Exterior,MarketHashName,ExternalImageUrl,PurchasePrice,CurrentPrice,PurchaseDate,Notes,CreatedUtc,UpdatedUtc FROM TrackedSkins WHERE UserId=p_user_id ORDER BY UpdatedUtc DESC$$
CREATE PROCEDURE sp_tracked_skins_create(IN p_user_id CHAR(36),IN p_skin_id CHAR(36),IN p_name VARCHAR(200),IN p_weapon VARCHAR(100),IN p_exterior VARCHAR(100),IN p_market_hash_name VARCHAR(255),IN p_external_image_url VARCHAR(2048),IN p_purchase_price DECIMAL(12,2),IN p_current_price DECIMAL(12,2),IN p_purchase_date DATE,IN p_notes TEXT) INSERT INTO TrackedSkins(SkinId,UserId,Name,Weapon,Exterior,MarketHashName,ExternalImageUrl,PurchasePrice,CurrentPrice,PurchaseDate,Notes,CreatedUtc,UpdatedUtc) VALUES(p_skin_id,p_user_id,p_name,p_weapon,p_exterior,p_market_hash_name,p_external_image_url,p_purchase_price,p_current_price,p_purchase_date,p_notes,UTC_TIMESTAMP(),UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_tracked_skins_update(IN p_user_id CHAR(36),IN p_skin_id CHAR(36),IN p_name VARCHAR(200),IN p_weapon VARCHAR(100),IN p_exterior VARCHAR(100),IN p_market_hash_name VARCHAR(255),IN p_external_image_url VARCHAR(2048),IN p_purchase_price DECIMAL(12,2),IN p_current_price DECIMAL(12,2),IN p_purchase_date DATE,IN p_notes TEXT) UPDATE TrackedSkins SET Name=p_name,Weapon=p_weapon,Exterior=p_exterior,MarketHashName=p_market_hash_name,ExternalImageUrl=p_external_image_url,PurchasePrice=p_purchase_price,CurrentPrice=p_current_price,PurchaseDate=p_purchase_date,Notes=p_notes,UpdatedUtc=UTC_TIMESTAMP() WHERE SkinId=p_skin_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_tracked_skins_delete(IN p_user_id CHAR(36),IN p_skin_id CHAR(36)) DELETE FROM TrackedSkins WHERE SkinId=p_skin_id AND UserId=p_user_id$$

DROP PROCEDURE IF EXISTS sp_dashboard_widget_order_get$$ DROP PROCEDURE IF EXISTS sp_dashboard_widget_order_set_bulk$$ DROP PROCEDURE IF EXISTS sp_dashboard_weather_locations_get$$ DROP PROCEDURE IF EXISTS sp_dashboard_weather_locations_create$$ DROP PROCEDURE IF EXISTS sp_dashboard_weather_locations_delete$$
CREATE PROCEDURE sp_dashboard_widget_order_get(IN p_user_id CHAR(36)) SELECT WidgetKey FROM DashboardWidgetOrders WHERE UserId=p_user_id ORDER BY SortOrder,WidgetKey$$
CREATE PROCEDURE sp_dashboard_widget_order_set_bulk(IN p_user_id CHAR(36),IN p_widget_keys JSON) BEGIN INSERT INTO DashboardWidgetOrders(UserId,WidgetKey,SortOrder,UpdatedUtc) SELECT p_user_id,p.WidgetKey,p.SortOrder,UTC_TIMESTAMP() FROM JSON_TABLE(p_widget_keys,'$[*]' COLUMNS(SortOrder FOR ORDINALITY,WidgetKey VARCHAR(50) PATH '$')) p ON DUPLICATE KEY UPDATE SortOrder=VALUES(SortOrder),UpdatedUtc=VALUES(UpdatedUtc); END$$
CREATE PROCEDURE sp_dashboard_weather_locations_get(IN p_user_id CHAR(36)) SELECT WeatherLocationId,DisplayName,Latitude,Longitude,CreatedUtc FROM DashboardWeatherLocations WHERE UserId=p_user_id ORDER BY CreatedUtc DESC$$
CREATE PROCEDURE sp_dashboard_weather_locations_create(IN p_user_id CHAR(36),IN p_weather_location_id CHAR(36),IN p_display_name VARCHAR(100),IN p_latitude DECIMAL(9,6),IN p_longitude DECIMAL(9,6)) INSERT INTO DashboardWeatherLocations(WeatherLocationId,UserId,DisplayName,Latitude,Longitude,CreatedUtc) VALUES(p_weather_location_id,p_user_id,p_display_name,p_latitude,p_longitude,UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_dashboard_weather_locations_delete(IN p_user_id CHAR(36),IN p_weather_location_id CHAR(36)) DELETE FROM DashboardWeatherLocations WHERE WeatherLocationId=p_weather_location_id AND UserId=p_user_id$$

DROP PROCEDURE IF EXISTS sp_cs_match_profiles_get$$ DROP PROCEDURE IF EXISTS sp_cs_match_profiles_create$$ DROP PROCEDURE IF EXISTS sp_cs_match_profiles_update$$ DROP PROCEDURE IF EXISTS sp_cs_match_profiles_delete$$
CREATE PROCEDURE sp_cs_match_profiles_get(IN p_user_id CHAR(36)) SELECT ProfileId,Name,SteamId,AvatarUrl,CreatedUtc FROM CSMatchProfiles WHERE UserId=p_user_id ORDER BY CreatedUtc$$
CREATE PROCEDURE sp_cs_match_profiles_create(IN p_user_id CHAR(36),IN p_profile_id CHAR(36),IN p_name VARCHAR(100),IN p_steam_id CHAR(17),IN p_avatar_url VARCHAR(2048)) INSERT INTO CSMatchProfiles(ProfileId,UserId,Name,SteamId,AvatarUrl,CreatedUtc) VALUES(p_profile_id,p_user_id,p_name,p_steam_id,NULLIF(p_avatar_url,''),UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_cs_match_profiles_update(IN p_user_id CHAR(36),IN p_profile_id CHAR(36),IN p_name VARCHAR(100),IN p_steam_id CHAR(17),IN p_avatar_url VARCHAR(2048)) UPDATE CSMatchProfiles SET Name=p_name,SteamId=p_steam_id,AvatarUrl=NULLIF(p_avatar_url,'') WHERE ProfileId=p_profile_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_cs_match_profiles_delete(IN p_user_id CHAR(36),IN p_profile_id CHAR(36)) DELETE FROM CSMatchProfiles WHERE ProfileId=p_profile_id AND UserId=p_user_id$$

DROP PROCEDURE IF EXISTS sp_cs_matches_get$$ DROP PROCEDURE IF EXISTS sp_cs_matches_get_range$$ DROP PROCEDURE IF EXISTS sp_cs_matches_create$$ DROP PROCEDURE IF EXISTS sp_cs_matches_update$$ DROP PROCEDURE IF EXISTS sp_cs_matches_delete$$ DROP PROCEDURE IF EXISTS sp_cs_matches_delete_all$$
CREATE PROCEDURE sp_cs_matches_get(IN p_user_id CHAR(36),IN p_profile_id CHAR(36)) SELECT MatchId,StartSide,MapName,GameType,TeamScore,OpponentScore,OvertimeCount,LeetifyMatchId,CreatedUtc,UpdatedUtc FROM CSMatches WHERE UserId=p_user_id AND ProfileId<=>p_profile_id ORDER BY CreatedUtc DESC$$
CREATE PROCEDURE sp_cs_matches_get_range(IN p_user_id CHAR(36),IN p_start_utc DATETIME,IN p_end_utc DATETIME) SELECT MatchId,StartSide,MapName,GameType,TeamScore,OpponentScore,OvertimeCount,LeetifyMatchId,CreatedUtc,UpdatedUtc FROM CSMatches WHERE UserId=p_user_id AND CreatedUtc>=p_start_utc AND CreatedUtc<p_end_utc ORDER BY CreatedUtc DESC$$
CREATE PROCEDURE sp_cs_matches_create(IN p_user_id CHAR(36),IN p_match_id CHAR(36),IN p_profile_id CHAR(36),IN p_start_side VARCHAR(2),IN p_map_name VARCHAR(100),IN p_game_type VARCHAR(100),IN p_team_score INT,IN p_opponent_score INT,IN p_overtime_count INT,IN p_leetify_match_id VARCHAR(100),IN p_created_utc DATETIME) INSERT IGNORE INTO CSMatches(MatchId,UserId,ProfileId,StartSide,MapName,GameType,TeamScore,OpponentScore,OvertimeCount,LeetifyMatchId,PlayedUtc,CreatedUtc,UpdatedUtc) VALUES(p_match_id,p_user_id,p_profile_id,p_start_side,p_map_name,p_game_type,p_team_score,p_opponent_score,p_overtime_count,NULLIF(p_leetify_match_id,''),COALESCE(p_created_utc,UTC_TIMESTAMP()),COALESCE(p_created_utc,UTC_TIMESTAMP()),UTC_TIMESTAMP())$$
CREATE PROCEDURE sp_cs_matches_update(IN p_user_id CHAR(36),IN p_match_id CHAR(36),IN p_start_side VARCHAR(2),IN p_map_name VARCHAR(100),IN p_game_type VARCHAR(100),IN p_team_score INT,IN p_opponent_score INT,IN p_overtime_count INT) UPDATE CSMatches SET StartSide=p_start_side,MapName=p_map_name,GameType=p_game_type,TeamScore=p_team_score,OpponentScore=p_opponent_score,OvertimeCount=p_overtime_count,UpdatedUtc=UTC_TIMESTAMP() WHERE MatchId=p_match_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_cs_matches_delete(IN p_user_id CHAR(36),IN p_match_id CHAR(36)) DELETE FROM CSMatches WHERE MatchId=p_match_id AND UserId=p_user_id$$
CREATE PROCEDURE sp_cs_matches_delete_all(IN p_user_id CHAR(36),IN p_profile_id CHAR(36)) DELETE FROM CSMatches WHERE UserId=p_user_id AND ProfileId<=>p_profile_id$$

DROP PROCEDURE IF EXISTS sp_cs_player_reports_count$$ DROP PROCEDURE IF EXISTS sp_cs_player_reports_create$$
CREATE PROCEDURE sp_cs_player_reports_count(IN p_steam64_id CHAR(17)) SELECT COUNT(*) FROM CSPlayerReports WHERE Steam64Id=p_steam64_id$$
CREATE PROCEDURE sp_cs_player_reports_create(IN p_report_id CHAR(36),IN p_user_id CHAR(36),IN p_steam64_id CHAR(17)) BEGIN INSERT IGNORE INTO CSPlayerReports(ReportId,UserId,Steam64Id,CreatedUtc) VALUES(p_report_id,p_user_id,p_steam64_id,UTC_TIMESTAMP()); SELECT ROW_COUNT(); END$$

DROP PROCEDURE IF EXISTS sp_cs_demo_catalog_get$$ DROP PROCEDURE IF EXISTS sp_cs_demo_catalog_refresh$$
CREATE PROCEDURE sp_cs_demo_catalog_get(IN p_user_id CHAR(36),IN p_steam64_id CHAR(17)) SELECT DemoId,Steam64Id,LeetifyMatchId,MapName,GameType,TeamScore,OpponentScore,IsWin,ReplayUrl,IsAvailable,PlayedAtUtc,RefreshedUtc FROM CSDemoCatalog WHERE UserId=p_user_id AND Steam64Id=p_steam64_id ORDER BY PlayedAtUtc DESC$$
CREATE PROCEDURE sp_cs_demo_catalog_refresh(IN p_user_id CHAR(36),IN p_steam64_id CHAR(17),IN p_demos JSON) BEGIN UPDATE CSDemoCatalog SET IsAvailable=0,ReplayUrl=NULL,RefreshedUtc=UTC_TIMESTAMP() WHERE UserId=p_user_id AND Steam64Id=p_steam64_id; INSERT INTO CSDemoCatalog(DemoId,UserId,Steam64Id,LeetifyMatchId,MapName,GameType,TeamScore,OpponentScore,IsWin,ReplayUrl,IsAvailable,PlayedAtUtc,RefreshedUtc) SELECT selected.DemoId,p_user_id,p_steam64_id,selected.LeetifyMatchId,selected.MapName,selected.GameType,selected.TeamScore,selected.OpponentScore,selected.IsWin,NULLIF(selected.ReplayUrl,''),selected.IsAvailable,selected.PlayedAtUtc,UTC_TIMESTAMP() FROM JSON_TABLE(p_demos,'$[*]' COLUMNS(DemoId CHAR(36) PATH '$.DemoId',LeetifyMatchId VARCHAR(100) PATH '$.LeetifyMatchId',MapName VARCHAR(100) PATH '$.MapName',GameType VARCHAR(100) PATH '$.GameType',TeamScore INT PATH '$.TeamScore',OpponentScore INT PATH '$.OpponentScore',IsWin TINYINT PATH '$.IsWin',ReplayUrl VARCHAR(2048) PATH '$.ReplayUrl',IsAvailable TINYINT PATH '$.IsAvailable',PlayedAtUtc DATETIME PATH '$.PlayedAtUtc')) AS selected ON DUPLICATE KEY UPDATE MapName=VALUES(MapName),GameType=VALUES(GameType),TeamScore=VALUES(TeamScore),OpponentScore=VALUES(OpponentScore),IsWin=VALUES(IsWin),ReplayUrl=VALUES(ReplayUrl),IsAvailable=VALUES(IsAvailable),PlayedAtUtc=VALUES(PlayedAtUtc),RefreshedUtc=UTC_TIMESTAMP(); END$$

DROP PROCEDURE IF EXISTS sp_application_logs_write_bulk$$ DROP PROCEDURE IF EXISTS sp_application_logs_get_page$$ DROP PROCEDURE IF EXISTS sp_application_logs_get_summary$$
CREATE PROCEDURE sp_application_logs_write_bulk(IN p_logs JSON) BEGIN INSERT IGNORE INTO ApplicationLogs(LogId,CapturedUtc,LogLevel,EventId,EventName,Category,Message,ExceptionText) SELECT selected.LogId,selected.CapturedUtc,selected.LogLevel,selected.EventId,NULLIF(selected.EventName,''),selected.Category,selected.Message,NULLIF(selected.ExceptionText,'') FROM JSON_TABLE(p_logs,'$[*]' COLUMNS(LogId CHAR(36) PATH '$.LogId',CapturedUtc DATETIME(6) PATH '$.CapturedUtc',LogLevel TINYINT PATH '$.Level',EventId INT PATH '$.EventId',EventName VARCHAR(250) PATH '$.EventName' NULL ON EMPTY,Category VARCHAR(500) PATH '$.Category',Message VARCHAR(10000) PATH '$.Message',ExceptionText VARCHAR(30000) PATH '$.Exception' NULL ON EMPTY)) AS selected; DELETE FROM ApplicationLogs WHERE CapturedUtc<UTC_TIMESTAMP(6)-INTERVAL 30 DAY; END$$
CREATE PROCEDURE sp_application_logs_get_page(IN p_minimum_level TINYINT,IN p_search VARCHAR(500),IN p_offset INT,IN p_page_size INT) SELECT LogId,CapturedUtc,LogLevel AS `Level`,EventId,EventName,Category,Message,ExceptionText AS `Exception` FROM ApplicationLogs WHERE LogLevel>=p_minimum_level AND (COALESCE(TRIM(p_search),'')='' OR Category LIKE CONCAT('%',TRIM(p_search) COLLATE utf8mb4_general_ci,'%') OR Message LIKE CONCAT('%',TRIM(p_search) COLLATE utf8mb4_general_ci,'%') OR ExceptionText LIKE CONCAT('%',TRIM(p_search) COLLATE utf8mb4_general_ci,'%')) ORDER BY CapturedUtc DESC,LogId DESC LIMIT p_offset,p_page_size$$
CREATE PROCEDURE sp_application_logs_get_summary(IN p_minimum_level TINYINT,IN p_search VARCHAR(500)) SELECT MIN(CapturedUtc) AS CaptureStartedUtc,COUNT(*) AS RetainedCount,COALESCE(SUM(CASE WHEN LogLevel=3 THEN 1 ELSE 0 END),0) AS WarningCount,COALESCE(SUM(CASE WHEN LogLevel=4 THEN 1 ELSE 0 END),0) AS ErrorCount,COALESCE(SUM(CASE WHEN LogLevel=5 THEN 1 ELSE 0 END),0) AS CriticalCount,COALESCE(SUM(CASE WHEN LogLevel>=p_minimum_level AND (COALESCE(TRIM(p_search),'')='' OR Category LIKE CONCAT('%',TRIM(p_search) COLLATE utf8mb4_general_ci,'%') OR Message LIKE CONCAT('%',TRIM(p_search) COLLATE utf8mb4_general_ci,'%') OR ExceptionText LIKE CONCAT('%',TRIM(p_search) COLLATE utf8mb4_general_ci,'%')) THEN 1 ELSE 0 END),0) AS FilteredCount FROM ApplicationLogs$$

DROP PROCEDURE IF EXISTS sp_tracker_items_get$$ DROP PROCEDURE IF EXISTS sp_tracker_items_create$$ DROP PROCEDURE IF EXISTS sp_tracker_items_update$$ DROP PROCEDURE IF EXISTS sp_tracker_items_move$$ DROP PROCEDURE IF EXISTS sp_tracker_items_set_status$$ DROP PROCEDURE IF EXISTS sp_tracker_items_delete$$ DROP PROCEDURE IF EXISTS sp_tracker_items_auto_close$$ DROP PROCEDURE IF EXISTS sp_tracker_items_get_closed$$ DROP PROCEDURE IF EXISTS sp_tracker_assignees_get$$ DROP PROCEDURE IF EXISTS sp_tracker_settings_get$$ DROP PROCEDURE IF EXISTS sp_tracker_settings_set$$
CREATE PROCEDURE sp_tracker_items_get() SELECT t.ItemId,t.Type,t.Title,t.Description,t.Area,t.Status,t.SortOrder,creator.DisplayName AS CreatedByDisplayName,t.AssignedToUserId,assignee.DisplayName AS AssignedToDisplayName,t.ShowOnDashboard,t.CreatedUtc,t.UpdatedUtc FROM TrackerItems t LEFT JOIN Users creator ON creator.UserId=t.CreatedByUserId LEFT JOIN Users assignee ON assignee.UserId=t.AssignedToUserId WHERE t.Status<>'Closed' ORDER BY t.Status,t.SortOrder,t.CreatedUtc$$
CREATE PROCEDURE sp_tracker_items_create(IN p_item_id CHAR(36),IN p_type VARCHAR(10),IN p_title VARCHAR(200),IN p_description TEXT,IN p_area VARCHAR(50),IN p_created_by_user_id CHAR(36),IN p_assigned_to_user_id CHAR(36),IN p_show_on_dashboard TINYINT(1)) INSERT INTO TrackerItems(ItemId,Type,Title,Description,Area,Status,SortOrder,CreatedByUserId,AssignedToUserId,ShowOnDashboard,CreatedUtc,UpdatedUtc) SELECT p_item_id,p_type,p_title,p_description,p_area,'Open',COALESCE(MAX(SortOrder)+1,0),p_created_by_user_id,NULLIF(p_assigned_to_user_id,''),p_show_on_dashboard,UTC_TIMESTAMP(),UTC_TIMESTAMP() FROM TrackerItems WHERE Status='Open'$$
CREATE PROCEDURE sp_tracker_items_update(IN p_item_id CHAR(36),IN p_type VARCHAR(10),IN p_title VARCHAR(200),IN p_description TEXT,IN p_area VARCHAR(50),IN p_status VARCHAR(20),IN p_assigned_to_user_id CHAR(36),IN p_show_on_dashboard TINYINT(1)) BEGIN UPDATE TrackerItems t SET t.ResolvedUtc=CASE WHEN p_status='Resolved' AND t.Status<>'Resolved' THEN UTC_TIMESTAMP() WHEN p_status<>'Resolved' THEN NULL ELSE t.ResolvedUtc END,t.Type=p_type,t.Title=p_title,t.Description=p_description,t.Area=p_area,t.SortOrder=IF(t.Status=p_status,t.SortOrder,COALESCE((SELECT MAX(o.SortOrder)+1 FROM (SELECT SortOrder FROM TrackerItems WHERE Status=p_status) AS o),0)),t.Status=p_status,t.AssignedToUserId=NULLIF(p_assigned_to_user_id,''),t.ShowOnDashboard=p_show_on_dashboard,t.UpdatedUtc=UTC_TIMESTAMP() WHERE t.ItemId=p_item_id; END$$
CREATE PROCEDURE sp_tracker_items_move(IN p_item_id CHAR(36),IN p_status VARCHAR(20),IN p_item_ids JSON) BEGIN UPDATE TrackerItems SET ResolvedUtc=CASE WHEN p_status='Resolved' AND Status<>'Resolved' THEN UTC_TIMESTAMP() WHEN p_status<>'Resolved' THEN NULL ELSE ResolvedUtc END,Status=p_status,UpdatedUtc=UTC_TIMESTAMP() WHERE ItemId=p_item_id; UPDATE TrackerItems t INNER JOIN JSON_TABLE(p_item_ids,'$[*]' COLUMNS(SortOrder FOR ORDINALITY,ItemId CHAR(36) PATH '$')) p ON p.ItemId=t.ItemId SET t.SortOrder=p.SortOrder; END$$
CREATE PROCEDURE sp_tracker_items_set_status(IN p_item_id CHAR(36),IN p_status VARCHAR(20)) BEGIN UPDATE TrackerItems t SET t.ResolvedUtc=CASE WHEN p_status='Resolved' AND t.Status<>'Resolved' THEN UTC_TIMESTAMP() WHEN p_status<>'Resolved' THEN NULL ELSE t.ResolvedUtc END,t.SortOrder=IF(t.Status=p_status,t.SortOrder,COALESCE((SELECT MAX(o.SortOrder)+1 FROM (SELECT SortOrder FROM TrackerItems WHERE Status=p_status) AS o),0)),t.Status=p_status,t.UpdatedUtc=UTC_TIMESTAMP() WHERE t.ItemId=p_item_id; END$$
CREATE PROCEDURE sp_tracker_items_delete(IN p_item_id CHAR(36)) DELETE FROM TrackerItems WHERE ItemId=p_item_id$$
CREATE PROCEDURE sp_tracker_items_auto_close(IN p_days INT) UPDATE TrackerItems SET Status='Closed',UpdatedUtc=UTC_TIMESTAMP() WHERE Status='Resolved' AND ResolvedUtc IS NOT NULL AND ResolvedUtc<=UTC_TIMESTAMP() - INTERVAL p_days DAY$$
CREATE PROCEDURE sp_tracker_items_get_closed() SELECT t.ItemId,t.Type,t.Title,t.Description,t.Area,t.Status,t.SortOrder,creator.DisplayName AS CreatedByDisplayName,t.AssignedToUserId,assignee.DisplayName AS AssignedToDisplayName,t.CreatedUtc,t.UpdatedUtc FROM TrackerItems t LEFT JOIN Users creator ON creator.UserId=t.CreatedByUserId LEFT JOIN Users assignee ON assignee.UserId=t.AssignedToUserId WHERE t.Status='Closed' ORDER BY t.UpdatedUtc DESC$$
CREATE PROCEDURE sp_tracker_assignees_get() SELECT UserId,DisplayName FROM Users WHERE IsActive=1 ORDER BY DisplayName$$
CREATE PROCEDURE sp_tracker_settings_get() SELECT AutoCloseAfterDays FROM TrackerSettings WHERE Id=1$$
CREATE PROCEDURE sp_tracker_settings_set(IN p_auto_close_after_days INT) UPDATE TrackerSettings SET AutoCloseAfterDays=p_auto_close_after_days,UpdatedUtc=UTC_TIMESTAMP() WHERE Id=1$$

DROP PROCEDURE IF EXISTS sp_paste_bin_settings_get$$ DROP PROCEDURE IF EXISTS sp_paste_bin_settings_update$$ DROP PROCEDURE IF EXISTS sp_paste_bin_pastes_get$$ DROP PROCEDURE IF EXISTS sp_paste_bin_paste_get_by_short_code$$ DROP PROCEDURE IF EXISTS sp_paste_bin_short_code_exists$$ DROP PROCEDURE IF EXISTS sp_paste_bin_paste_create$$ DROP PROCEDURE IF EXISTS sp_paste_bin_paste_delete$$ DROP PROCEDURE IF EXISTS sp_paste_bin_expired_pastes_get$$ DROP PROCEDURE IF EXISTS sp_paste_bin_expired_pastes_delete$$ DROP PROCEDURE IF EXISTS sp_paste_bin_stored_file_names_get$$
CREATE PROCEDURE sp_paste_bin_settings_get() SELECT MaximumUploadSizeMb,UpdatedUtc FROM PasteBinSettings WHERE Id=1$$
CREATE PROCEDURE sp_paste_bin_settings_update(IN p_maximum_upload_size_mb INT) BEGIN IF p_maximum_upload_size_mb<1 OR p_maximum_upload_size_mb>50 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Paste Bin upload limit must be between 1 and 50 MB'; END IF; UPDATE PasteBinSettings SET MaximumUploadSizeMb=p_maximum_upload_size_mb,UpdatedUtc=UTC_TIMESTAMP() WHERE Id=1; END$$
CREATE PROCEDURE sp_paste_bin_pastes_get() SELECT p.PasteId,p.CreatedByUserId,u.DisplayName AS CreatedByDisplayName,p.ShortCode,p.Title,p.Language,NULL AS Content,IF(p.PasswordHash IS NULL,NULL,'protected') AS PasswordHash,p.CreatedUtc,p.ExpiresUtc,f.PasteFileId,f.OriginalFileName,NULL AS StoredFileName,f.ContentType AS FileContentType,f.FileExtension,f.FileSizeBytes,f.CreatedUtc AS FileCreatedUtc FROM PasteBinPastes p INNER JOIN Users u ON u.UserId=p.CreatedByUserId LEFT JOIN PasteBinFiles f ON f.PasteId=p.PasteId WHERE p.ExpiresUtc IS NULL OR p.ExpiresUtc>UTC_TIMESTAMP() ORDER BY p.CreatedUtc DESC$$
CREATE PROCEDURE sp_paste_bin_paste_get_by_short_code(IN p_short_code VARCHAR(16)) SELECT p.PasteId,p.CreatedByUserId,u.DisplayName AS CreatedByDisplayName,p.ShortCode,p.Title,p.Language,p.Content,p.PasswordHash,p.CreatedUtc,p.ExpiresUtc,f.PasteFileId,f.OriginalFileName,f.StoredFileName,f.ContentType AS FileContentType,f.FileExtension,f.FileSizeBytes,f.CreatedUtc AS FileCreatedUtc FROM PasteBinPastes p INNER JOIN Users u ON u.UserId=p.CreatedByUserId LEFT JOIN PasteBinFiles f ON f.PasteId=p.PasteId WHERE p.ShortCode=p_short_code AND (p.ExpiresUtc IS NULL OR p.ExpiresUtc>UTC_TIMESTAMP()) LIMIT 1$$
CREATE PROCEDURE sp_paste_bin_short_code_exists(IN p_short_code VARCHAR(16)) SELECT EXISTS(SELECT 1 FROM PasteBinPastes WHERE ShortCode=p_short_code)$$
CREATE PROCEDURE sp_paste_bin_paste_create(IN p_paste_id CHAR(36),IN p_created_by_user_id CHAR(36),IN p_short_code VARCHAR(16),IN p_title VARCHAR(200),IN p_language VARCHAR(30),IN p_content MEDIUMTEXT,IN p_password_hash VARCHAR(512),IN p_expires_utc DATETIME,IN p_paste_file_id CHAR(36),IN p_original_file_name VARCHAR(255),IN p_stored_file_name CHAR(36),IN p_content_type VARCHAR(150),IN p_file_extension VARCHAR(20),IN p_file_size_bytes BIGINT UNSIGNED) BEGIN DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END; START TRANSACTION; INSERT INTO PasteBinPastes(PasteId,CreatedByUserId,ShortCode,Title,Language,Content,PasswordHash,CreatedUtc,ExpiresUtc) VALUES(p_paste_id,p_created_by_user_id,p_short_code,p_title,p_language,p_content,p_password_hash,UTC_TIMESTAMP(),p_expires_utc); IF p_paste_file_id IS NOT NULL THEN INSERT INTO PasteBinFiles(PasteFileId,PasteId,OriginalFileName,StoredFileName,ContentType,FileExtension,FileSizeBytes,CreatedUtc) VALUES(p_paste_file_id,p_paste_id,p_original_file_name,p_stored_file_name,p_content_type,p_file_extension,p_file_size_bytes,UTC_TIMESTAMP()); END IF; COMMIT; END$$
CREATE PROCEDURE sp_paste_bin_paste_delete(IN p_paste_id CHAR(36),IN p_user_id CHAR(36)) BEGIN DECLARE v_stored_file_name CHAR(36) DEFAULT NULL; IF EXISTS(SELECT 1 FROM PasteBinPastes WHERE PasteId=p_paste_id AND CreatedByUserId=p_user_id) THEN SELECT StoredFileName INTO v_stored_file_name FROM PasteBinFiles WHERE PasteId=p_paste_id LIMIT 1; DELETE FROM PasteBinPastes WHERE PasteId=p_paste_id AND CreatedByUserId=p_user_id; SELECT v_stored_file_name AS StoredFileName; END IF; END$$
CREATE PROCEDURE sp_paste_bin_expired_pastes_get() SELECT p.PasteId,f.StoredFileName FROM PasteBinPastes p LEFT JOIN PasteBinFiles f ON f.PasteId=p.PasteId WHERE p.ExpiresUtc IS NOT NULL AND p.ExpiresUtc<=UTC_TIMESTAMP()$$
CREATE PROCEDURE sp_paste_bin_expired_pastes_delete() DELETE FROM PasteBinPastes WHERE ExpiresUtc IS NOT NULL AND ExpiresUtc<=UTC_TIMESTAMP()$$
CREATE PROCEDURE sp_paste_bin_stored_file_names_get() SELECT f.StoredFileName FROM PasteBinFiles f INNER JOIN PasteBinPastes p ON p.PasteId=f.PasteId WHERE p.ExpiresUtc IS NULL OR p.ExpiresUtc>UTC_TIMESTAMP()$$

DROP PROCEDURE IF EXISTS sp_case_opening_history_get$$ DROP PROCEDURE IF EXISTS sp_case_opening_history_create$$ DROP PROCEDURE IF EXISTS sp_case_opening_history_clear$$ DROP PROCEDURE IF EXISTS sp_case_opening_statistics_get$$
CREATE PROCEDURE sp_case_opening_history_get(IN p_user_id CHAR(36)) SELECT OpeningId,UserId,CaseKey,SourceItemId,ItemName,MarketHashName,ImageUrl,Description,WeaponName,PatternName,PaintIndex,Phase,RarityKey,RarityName,RarityColor,Wear,IsStatTrak,IsRareSpecial,SupportsStatTrak,MinFloat,MaxFloat,FloatValue,PatternSeed,EstimatedPrice,OpenedUtc FROM CaseOpeningHistory WHERE UserId=p_user_id ORDER BY OpenedUtc DESC,OpeningId DESC$$
CREATE PROCEDURE sp_case_opening_history_create(IN p_user_id CHAR(36),IN p_opening_id CHAR(36),IN p_case_key VARCHAR(80),IN p_source_item_id VARCHAR(160),IN p_item_name VARCHAR(255),IN p_market_hash_name VARCHAR(300),IN p_image_url VARCHAR(2048),IN p_description TEXT,IN p_weapon_name VARCHAR(100),IN p_pattern_name VARCHAR(150),IN p_paint_index VARCHAR(20),IN p_phase VARCHAR(50),IN p_rarity_key VARCHAR(30),IN p_rarity_name VARCHAR(80),IN p_rarity_color CHAR(7),IN p_wear VARCHAR(40),IN p_is_stat_trak TINYINT(1),IN p_is_rare_special TINYINT(1),IN p_supports_stat_trak TINYINT(1),IN p_min_float DECIMAL(9,6),IN p_max_float DECIMAL(9,6),IN p_float_value DECIMAL(9,6),IN p_pattern_seed INT,IN p_estimated_price DECIMAL(12,2)) INSERT INTO CaseOpeningHistory(OpeningId,UserId,CaseKey,SourceItemId,ItemName,MarketHashName,ImageUrl,Description,WeaponName,PatternName,PaintIndex,Phase,RarityKey,RarityName,RarityColor,Wear,IsStatTrak,IsRareSpecial,SupportsStatTrak,MinFloat,MaxFloat,FloatValue,PatternSeed,EstimatedPrice,OpenedUtc) VALUES(p_opening_id,p_user_id,p_case_key,p_source_item_id,p_item_name,p_market_hash_name,p_image_url,p_description,p_weapon_name,p_pattern_name,p_paint_index,p_phase,p_rarity_key,p_rarity_name,p_rarity_color,p_wear,p_is_stat_trak,p_is_rare_special,p_supports_stat_trak,p_min_float,p_max_float,p_float_value,p_pattern_seed,p_estimated_price,UTC_TIMESTAMP(6))$$
CREATE PROCEDURE sp_case_opening_history_clear(IN p_user_id CHAR(36)) DELETE FROM CaseOpeningHistory WHERE UserId=p_user_id$$
CREATE PROCEDURE sp_case_opening_statistics_get(IN p_user_id CHAR(36),IN p_case_key VARCHAR(80),IN p_target_rarity_key VARCHAR(30)) BEGIN DECLARE v_last_target_utc DATETIME(6) DEFAULT NULL; SELECT MAX(OpenedUtc) INTO v_last_target_utc FROM CaseOpeningHistory WHERE UserId=p_user_id AND CaseKey=p_case_key AND RarityKey=p_target_rarity_key; SELECT COUNT(*) AS TotalOpenings,COALESCE(SUM(CASE WHEN RarityKey=p_target_rarity_key THEN 1 ELSE 0 END),0) AS TargetPulls,CASE WHEN v_last_target_utc IS NULL THEN COUNT(*) ELSE COALESCE(SUM(CASE WHEN OpenedUtc>v_last_target_utc THEN 1 ELSE 0 END),0) END AS CurrentDryStreak,v_last_target_utc AS LastTargetOpenedUtc FROM CaseOpeningHistory WHERE UserId=p_user_id AND CaseKey=p_case_key; END$$

DELIMITER ;
