namespace PersonalTools.Classes.PasteBin;

using PersonalTools.Entities.PasteBin;

public interface IPasteBinFileStorage
{
    Task<(string StoredFileName, long FileSizeBytes)> StoreFile(Stream source, long maximumBytes, CancellationToken cancellationToken);
    FileStream OpenRead(string storedFileName);
    Task DeleteFile(string? storedFileName);
    IEnumerable<FileInfo> GetStoredFiles();
}

public sealed class PasteBinFileStorage : IPasteBinFileStorage
{
    private readonly string _storagePath;

    public PasteBinFileStorage(IConfiguration configuration)
    {
        string fallback = OperatingSystem.IsWindows()
            ? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "PersonalTools", "PasteBin")
            : "/var/lib/personaltools/paste-bin";
        _storagePath = Path.GetFullPath(configuration["PasteBin:StoragePath"] ?? fallback);
        Directory.CreateDirectory(_storagePath);
    }

    public async Task<(string StoredFileName, long FileSizeBytes)> StoreFile(Stream source, long maximumBytes, CancellationToken cancellationToken)
    {
        string storedFileName = $"{Guid.NewGuid():N}.bin";
        string path = ResolveStoredPath(storedFileName);
        long totalBytes = 0;
        byte[] buffer = new byte[81_920];

        try
        {
            await using FileStream destination = new(path, FileMode.CreateNew, FileAccess.Write, FileShare.None, buffer.Length, FileOptions.Asynchronous);
            int bytesRead;
            while ((bytesRead = await source.ReadAsync(buffer.AsMemory(0, buffer.Length), cancellationToken)) > 0)
            {
                totalBytes += bytesRead;
                if (totalBytes > maximumBytes)
                    throw new PasteBinAccessException($"The selected file exceeds the current {maximumBytes / 1024 / 1024} MB Paste Bin upload limit.");

                await destination.WriteAsync(buffer.AsMemory(0, bytesRead), cancellationToken);
            }

            if (totalBytes == 0)
                throw new PasteBinAccessException("The selected file is empty.");

            return (storedFileName, totalBytes);
        }
        catch
        {
            await DeleteFile(storedFileName);
            throw;
        }
    }

    public FileStream OpenRead(string storedFileName) => new(ResolveStoredPath(storedFileName), FileMode.Open, FileAccess.Read, FileShare.Read, 81_920, FileOptions.Asynchronous | FileOptions.SequentialScan);

    public Task DeleteFile(string? storedFileName)
    {
        if (!string.IsNullOrWhiteSpace(storedFileName))
        {
            string path = ResolveStoredPath(storedFileName);
            if (File.Exists(path))
                File.Delete(path);
        }
        return Task.CompletedTask;
    }

    public IEnumerable<FileInfo> GetStoredFiles() => new DirectoryInfo(_storagePath).EnumerateFiles("*.bin", SearchOption.TopDirectoryOnly);

    private string ResolveStoredPath(string storedFileName)
    {
        // Stored names are generated by the server. This final check prevents a future database
        // or maintenance mistake from turning a download or cleanup into path traversal.
        if (storedFileName.Length != 36 || !storedFileName.EndsWith(".bin", StringComparison.OrdinalIgnoreCase) ||
            !Guid.TryParseExact(storedFileName[..32], "N", out _))
            throw new InvalidOperationException("The stored Paste Bin filename was invalid.");

        string path = Path.GetFullPath(Path.Combine(_storagePath, storedFileName));
        if (!string.Equals(Path.GetDirectoryName(path), _storagePath, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("The stored Paste Bin path was invalid.");
        return path;
    }
}
